/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SignatureVerifyingPaymasterV07FactoryInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "IMPLEMENTATION_SALT"
      | "PROXY_ADMIN_SALT"
      | "PROXY_SALT"
      | "computeAddresses"
      | "deployPaymaster"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "IMPLEMENTATION_SALT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROXY_ADMIN_SALT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROXY_SALT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployPaymaster",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "IMPLEMENTATION_SALT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROXY_ADMIN_SALT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PROXY_SALT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "computeAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployPaymaster",
    data: BytesLike
  ): Result;
}

export interface SignatureVerifyingPaymasterV07Factory extends BaseContract {
  connect(
    runner?: ContractRunner | null
  ): SignatureVerifyingPaymasterV07Factory;
  waitForDeployment(): Promise<this>;

  interface: SignatureVerifyingPaymasterV07FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IMPLEMENTATION_SALT: TypedContractMethod<[], [string], "view">;

  PROXY_ADMIN_SALT: TypedContractMethod<[], [string], "view">;

  PROXY_SALT: TypedContractMethod<[], [string], "view">;

  computeAddresses: TypedContractMethod<
    [],
    [
      [string, string, string] & {
        implementation: string;
        proxyAdmin: string;
        proxy: string;
      }
    ],
    "view"
  >;

  deployPaymaster: TypedContractMethod<
    [entryPoint: AddressLike, verifyingSigner: AddressLike, owner: AddressLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IMPLEMENTATION_SALT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROXY_ADMIN_SALT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROXY_SALT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "computeAddresses"
  ): TypedContractMethod<
    [],
    [
      [string, string, string] & {
        implementation: string;
        proxyAdmin: string;
        proxy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployPaymaster"
  ): TypedContractMethod<
    [entryPoint: AddressLike, verifyingSigner: AddressLike, owner: AddressLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
